/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Psicologo;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author YareMtz
 */
public class JFFormatoEgreso extends javax.swing.JFrame {

    /**
     * Creates new form JFFormatoEgreso
     */
    public JFFormatoEgreso() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jTabbedPane1.setToolTipTextAt(0, "<html>1. Tipo de egreso<br>2. Fase en la que ocurre el egreso<br>3. Motivo del egreso<br> 4. Resumen de tratamiento<br>5. Impresión diagnostica (Diagnostico inicial)</html>");
        jTabbedPane1.setToolTipTextAt(1, "<html>5. Impresión diagnostica (Diagnostico final)<br>6. Pronostico al egreso<br>7. Sugerencias terapéuticas y condiciones al egresar<br>8. Observaciones</html>");
        Image icon = new ImageIcon(getClass().getResource("/imagenes/solo-unemecapa.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        labelIcon4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        etiquetaExp = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Parte_1 = new javax.swing.JPanel();
        btnSave1 = new javax.swing.JButton();
        goBack1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        rb1AltaPorMejoria = new javax.swing.JRadioButton();
        rb1CumplioObjetivosdelTx = new javax.swing.JRadioButton();
        rb1AbandonodelTxSinMejoria = new javax.swing.JRadioButton();
        rb1AbandonodelTexConMejoria = new javax.swing.JRadioButton();
        rb1Baja = new javax.swing.JRadioButton();
        rb1VoluntarioSinMejoria = new javax.swing.JRadioButton();
        rb1VoluntarioConMejoria = new javax.swing.JRadioButton();
        rb2TratamientoReinsercionSocial = new javax.swing.JRadioButton();
        rb2FaseDiagnostica = new javax.swing.JRadioButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txt4_areamedica = new javax.swing.JTextArea();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        txt3_MotivoEgreso = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        txt4_areapsicologia = new javax.swing.JTextArea();
        jLabel90 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        txt4_areasocial = new javax.swing.JTextArea();
        jLabel92 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        txt5_areamedica = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        txt5_areasocial = new javax.swing.JTextArea();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        txt5_areapsicologia = new javax.swing.JTextArea();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JButton();
        Parte_2 = new javax.swing.JPanel();
        btnSave2 = new javax.swing.JButton();
        btnRegresar2 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        txt5_Dareamedica = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        txt5_Dareasocial = new javax.swing.JTextArea();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        txt5_Dareapsicologia = new javax.swing.JTextArea();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jScrollPane28 = new javax.swing.JScrollPane();
        txt6_PronosticoEgreso = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        txt7_Sugerencias = new javax.swing.JTextArea();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jScrollPane30 = new javax.swing.JScrollPane();
        txt8_Observaciones = new javax.swing.JTextArea();
        btnAnterior2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Unidad de Especialidad Médica - Centro de Atención Primaria en Adicciones");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel10FocusLost(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGO.png"))); // NOI18N
        jPanel10.add(labelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, -1, 60));

        jPanel11.setBackground(new java.awt.Color(139, 165, 155));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chilpancingo, Guerrero, México.");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Calle Venustiano Carranza No. 18, Col. 20 de noviembre, C.P. 39096");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 20));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1340, 30));

        jPanel13.setBackground(new java.awt.Color(0, 138, 58));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaExp.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        etiquetaExp.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaExp.setText("Formato de egreso - Expediente: #### - ####");
        jPanel13.add(etiquetaExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 30));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N

        Parte_1.setBackground(new java.awt.Color(255, 255, 255));
        Parte_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave1.setBackground(new java.awt.Color(255, 255, 255));
        btnSave1.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-save.png"))); // NOI18N
        btnSave1.setToolTipText("Guardar los datos del registro");
        Parte_1.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, -1, -1));

        goBack1.setBackground(new java.awt.Color(255, 255, 255));
        goBack1.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        goBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-home.png"))); // NOI18N
        Parte_1.add(goBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1201, 582, -1, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Heiti TC", 0, 13))); // NOI18N
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setText("1.- Tipo de egreso:");
        jLabel83.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel17.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        buttonGroup1.add(rb1AltaPorMejoria);
        rb1AltaPorMejoria.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb1AltaPorMejoria.setText("Alta por mejoría");
        rb1AltaPorMejoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1AltaPorMejoriaActionPerformed(evt);
            }
        });
        jPanel17.add(rb1AltaPorMejoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 40));

        buttonGroup1.add(rb1CumplioObjetivosdelTx);
        rb1CumplioObjetivosdelTx.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb1CumplioObjetivosdelTx.setText("Cumplió con los objetivos del Tx.");
        rb1CumplioObjetivosdelTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1CumplioObjetivosdelTxActionPerformed(evt);
            }
        });
        jPanel17.add(rb1CumplioObjetivosdelTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 40));

        buttonGroup1.add(rb1AbandonodelTxSinMejoria);
        rb1AbandonodelTxSinMejoria.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb1AbandonodelTxSinMejoria.setText("Abandono del Tx sin mejoría");
        rb1AbandonodelTxSinMejoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1AbandonodelTxSinMejoriaActionPerformed(evt);
            }
        });
        jPanel17.add(rb1AbandonodelTxSinMejoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 40));

        buttonGroup1.add(rb1AbandonodelTexConMejoria);
        rb1AbandonodelTexConMejoria.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb1AbandonodelTexConMejoria.setText("Abandono del Tx con mejoría");
        rb1AbandonodelTexConMejoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1AbandonodelTexConMejoriaActionPerformed(evt);
            }
        });
        jPanel17.add(rb1AbandonodelTexConMejoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 40));

        buttonGroup1.add(rb1Baja);
        rb1Baja.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb1Baja.setText("Baja");
        rb1Baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1BajaActionPerformed(evt);
            }
        });
        jPanel17.add(rb1Baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, 40));

        buttonGroup1.add(rb1VoluntarioSinMejoria);
        rb1VoluntarioSinMejoria.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb1VoluntarioSinMejoria.setText("Voluntario sin mejoría");
        rb1VoluntarioSinMejoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1VoluntarioSinMejoriaActionPerformed(evt);
            }
        });
        jPanel17.add(rb1VoluntarioSinMejoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, 40));

        buttonGroup1.add(rb1VoluntarioConMejoria);
        rb1VoluntarioConMejoria.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb1VoluntarioConMejoria.setText("Voluntario con mejoría");
        rb1VoluntarioConMejoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1VoluntarioConMejoriaActionPerformed(evt);
            }
        });
        jPanel17.add(rb1VoluntarioConMejoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, 40));

        buttonGroup2.add(rb2TratamientoReinsercionSocial);
        rb2TratamientoReinsercionSocial.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb2TratamientoReinsercionSocial.setText("Tratamiento y reinserción social");
        rb2TratamientoReinsercionSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2TratamientoReinsercionSocialActionPerformed(evt);
            }
        });
        jPanel17.add(rb2TratamientoReinsercionSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 550, 40));

        buttonGroup2.add(rb2FaseDiagnostica);
        rb2FaseDiagnostica.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        rb2FaseDiagnostica.setText("Fase diagnóstica");
        rb2FaseDiagnostica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2FaseDiagnosticaActionPerformed(evt);
            }
        });
        jPanel17.add(rb2FaseDiagnostica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 550, 40));

        jLabel84.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel84.setText("3.- Motivo del egreso:");
        jPanel17.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabel85.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel85.setText("Área médica");
        jPanel17.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 270, -1));

        txt4_areamedica.setColumns(20);
        txt4_areamedica.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt4_areamedica.setLineWrap(true);
        txt4_areamedica.setRows(3);
        txt4_areamedica.setWrapStyleWord(true);
        txt4_areamedica.setBorder(null);
        txt4_areamedica.setOpaque(false);
        txt4_areamedica.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt4_areamedica.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane15.setViewportView(txt4_areamedica);

        jPanel17.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, 110));

        jLabel88.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel88.setText("2.- Fase en la que ocurre el egreso");
        jPanel17.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 660, -1));

        jLabel89.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel89.setText("4.- Resumen del tratamiento:");
        jPanel17.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, -1));

        txt3_MotivoEgreso.setColumns(20);
        txt3_MotivoEgreso.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt3_MotivoEgreso.setLineWrap(true);
        txt3_MotivoEgreso.setRows(3);
        txt3_MotivoEgreso.setWrapStyleWord(true);
        txt3_MotivoEgreso.setBorder(null);
        txt3_MotivoEgreso.setOpaque(false);
        txt3_MotivoEgreso.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt3_MotivoEgreso.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane18.setViewportView(txt3_MotivoEgreso);

        jPanel17.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 490, 100));

        txt4_areapsicologia.setColumns(20);
        txt4_areapsicologia.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt4_areapsicologia.setLineWrap(true);
        txt4_areapsicologia.setRows(3);
        txt4_areapsicologia.setWrapStyleWord(true);
        txt4_areapsicologia.setBorder(null);
        txt4_areapsicologia.setOpaque(false);
        txt4_areapsicologia.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt4_areapsicologia.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane20.setViewportView(txt4_areapsicologia);

        jPanel17.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 350, 110));

        jLabel90.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel90.setText("Área de psicología");
        jPanel17.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 270, -1));

        txt4_areasocial.setColumns(20);
        txt4_areasocial.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt4_areasocial.setLineWrap(true);
        txt4_areasocial.setRows(3);
        txt4_areasocial.setWrapStyleWord(true);
        txt4_areasocial.setBorder(null);
        txt4_areasocial.setOpaque(false);
        txt4_areasocial.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt4_areasocial.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane22.setViewportView(txt4_areasocial);

        jPanel17.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 350, 110));

        jLabel92.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel92.setText("Área social");
        jPanel17.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 270, -1));

        jLabel91.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("Diagnóstico inicial");
        jPanel17.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 1160, -1));

        txt5_areamedica.setColumns(20);
        txt5_areamedica.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt5_areamedica.setLineWrap(true);
        txt5_areamedica.setRows(3);
        txt5_areamedica.setWrapStyleWord(true);
        txt5_areamedica.setBorder(null);
        txt5_areamedica.setOpaque(false);
        txt5_areamedica.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt5_areamedica.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane21.setViewportView(txt5_areamedica);

        jPanel17.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 350, 120));

        txt5_areasocial.setColumns(20);
        txt5_areasocial.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt5_areasocial.setLineWrap(true);
        txt5_areasocial.setRows(3);
        txt5_areasocial.setWrapStyleWord(true);
        txt5_areasocial.setBorder(null);
        txt5_areasocial.setOpaque(false);
        txt5_areasocial.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt5_areasocial.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane23.setViewportView(txt5_areasocial);

        jPanel17.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 350, 120));

        jLabel93.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel93.setText("Área social");
        jPanel17.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 270, -1));

        jLabel94.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel94.setText("Área de psicología");
        jPanel17.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 270, -1));

        txt5_areapsicologia.setColumns(20);
        txt5_areapsicologia.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt5_areapsicologia.setLineWrap(true);
        txt5_areapsicologia.setRows(3);
        txt5_areapsicologia.setWrapStyleWord(true);
        txt5_areapsicologia.setBorder(null);
        txt5_areapsicologia.setOpaque(false);
        txt5_areapsicologia.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt5_areapsicologia.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane24.setViewportView(txt5_areapsicologia);

        jPanel17.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 350, 120));

        jLabel95.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel95.setText("5.- Impresión diagnóstica");
        jPanel17.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 660, -1));

        jLabel96.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel96.setText("Área médica");
        jPanel17.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 270, 20));

        Parte_1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, 1230, 570));

        btnSiguiente1.setBackground(new java.awt.Color(255, 255, 255));
        btnSiguiente1.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnSiguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-double_right.png"))); // NOI18N
        btnSiguiente1.setToolTipText("Siguiente parte del formato de egreso");
        Parte_1.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, 40, -1));

        jTabbedPane1.addTab("Primera parte", Parte_1);

        Parte_2.setBackground(new java.awt.Color(255, 255, 255));

        btnSave2.setBackground(new java.awt.Color(255, 255, 255));
        btnSave2.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-save.png"))); // NOI18N
        btnSave2.setToolTipText("Guardar los datos del registro");

        btnRegresar2.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar2.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnRegresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-home.png"))); // NOI18N
        btnRegresar2.setToolTipText("Regresar al menu principal");

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Heiti TC", 0, 13))); // NOI18N
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel97.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("Diagnóstico final");
        jPanel18.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1160, -1));

        txt5_Dareamedica.setColumns(20);
        txt5_Dareamedica.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt5_Dareamedica.setLineWrap(true);
        txt5_Dareamedica.setRows(3);
        txt5_Dareamedica.setWrapStyleWord(true);
        txt5_Dareamedica.setBorder(null);
        txt5_Dareamedica.setOpaque(false);
        txt5_Dareamedica.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt5_Dareamedica.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane25.setViewportView(txt5_Dareamedica);

        jPanel18.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, 120));

        txt5_Dareasocial.setColumns(20);
        txt5_Dareasocial.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt5_Dareasocial.setLineWrap(true);
        txt5_Dareasocial.setRows(3);
        txt5_Dareasocial.setWrapStyleWord(true);
        txt5_Dareasocial.setBorder(null);
        txt5_Dareasocial.setOpaque(false);
        txt5_Dareasocial.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt5_Dareasocial.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane26.setViewportView(txt5_Dareasocial);

        jPanel18.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 350, 120));

        jLabel98.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel98.setText("Área social");
        jPanel18.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 270, -1));

        jLabel99.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel99.setText("Área de psicología");
        jPanel18.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 270, -1));

        txt5_Dareapsicologia.setColumns(20);
        txt5_Dareapsicologia.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt5_Dareapsicologia.setLineWrap(true);
        txt5_Dareapsicologia.setRows(3);
        txt5_Dareapsicologia.setWrapStyleWord(true);
        txt5_Dareapsicologia.setBorder(null);
        txt5_Dareapsicologia.setOpaque(false);
        txt5_Dareapsicologia.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt5_Dareapsicologia.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane27.setViewportView(txt5_Dareapsicologia);

        jPanel18.add(jScrollPane27, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 350, 120));

        jLabel100.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel100.setText("5.- Impresión diagnóstica");
        jPanel18.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 660, -1));

        jLabel101.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel101.setText("Área médica");
        jPanel18.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 270, 20));

        jLabel102.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel102.setText("6.- Pronóstico al egreso");
        jPanel18.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 270, 20));

        txt6_PronosticoEgreso.setColumns(20);
        txt6_PronosticoEgreso.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt6_PronosticoEgreso.setLineWrap(true);
        txt6_PronosticoEgreso.setRows(3);
        txt6_PronosticoEgreso.setWrapStyleWord(true);
        txt6_PronosticoEgreso.setBorder(null);
        txt6_PronosticoEgreso.setOpaque(false);
        txt6_PronosticoEgreso.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt6_PronosticoEgreso.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane28.setViewportView(txt6_PronosticoEgreso);

        jPanel18.add(jScrollPane28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 550, 80));

        txt7_Sugerencias.setColumns(20);
        txt7_Sugerencias.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt7_Sugerencias.setLineWrap(true);
        txt7_Sugerencias.setRows(3);
        txt7_Sugerencias.setWrapStyleWord(true);
        txt7_Sugerencias.setBorder(null);
        txt7_Sugerencias.setOpaque(false);
        txt7_Sugerencias.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt7_Sugerencias.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane29.setViewportView(txt7_Sugerencias);

        jPanel18.add(jScrollPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 550, 80));

        jLabel103.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel103.setText("7.- Sugerencias terapéuticas y condiciones al egresar");
        jPanel18.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 550, 20));

        jLabel104.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel104.setText("8.- Observaciones");
        jPanel18.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 270, 20));

        txt8_Observaciones.setColumns(20);
        txt8_Observaciones.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txt8_Observaciones.setLineWrap(true);
        txt8_Observaciones.setRows(3);
        txt8_Observaciones.setWrapStyleWord(true);
        txt8_Observaciones.setBorder(null);
        txt8_Observaciones.setOpaque(false);
        txt8_Observaciones.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt8_Observaciones.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane30.setViewportView(txt8_Observaciones);

        jPanel18.add(jScrollPane30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 550, 80));

        btnAnterior2.setBackground(new java.awt.Color(255, 255, 255));
        btnAnterior2.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnAnterior2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-double_left.png"))); // NOI18N
        btnAnterior2.setToolTipText("Ir a la etapa anterior");

        javax.swing.GroupLayout Parte_2Layout = new javax.swing.GroupLayout(Parte_2);
        Parte_2.setLayout(Parte_2Layout);
        Parte_2Layout.setHorizontalGroup(
            Parte_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Parte_2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(Parte_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Parte_2Layout.createSequentialGroup()
                        .addComponent(btnAnterior2)
                        .addGap(114, 114, 114)
                        .addComponent(btnSave2)
                        .addGap(569, 569, 569)
                        .addComponent(btnRegresar2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Parte_2Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        Parte_2Layout.setVerticalGroup(
            Parte_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Parte_2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Parte_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnterior2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Segunda parte", Parte_2);

        jPanel10.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1290, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel10FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10FocusLost

    private void rb1AltaPorMejoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1AltaPorMejoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1AltaPorMejoriaActionPerformed

    private void rb1CumplioObjetivosdelTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1CumplioObjetivosdelTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1CumplioObjetivosdelTxActionPerformed

    private void rb1AbandonodelTxSinMejoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1AbandonodelTxSinMejoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1AbandonodelTxSinMejoriaActionPerformed

    private void rb1AbandonodelTexConMejoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1AbandonodelTexConMejoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1AbandonodelTexConMejoriaActionPerformed

    private void rb1BajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1BajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1BajaActionPerformed

    private void rb1VoluntarioSinMejoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1VoluntarioSinMejoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1VoluntarioSinMejoriaActionPerformed

    private void rb1VoluntarioConMejoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1VoluntarioConMejoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1VoluntarioConMejoriaActionPerformed

    private void rb2TratamientoReinsercionSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2TratamientoReinsercionSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2TratamientoReinsercionSocialActionPerformed

    private void rb2FaseDiagnosticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2FaseDiagnosticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2FaseDiagnosticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFormatoEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFormatoEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFormatoEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFormatoEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFormatoEgreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Parte_1;
    public javax.swing.JPanel Parte_2;
    public javax.swing.JButton btnAnterior2;
    public javax.swing.JButton btnRegresar2;
    public javax.swing.JButton btnSave1;
    public javax.swing.JButton btnSave2;
    public javax.swing.JButton btnSiguiente1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JLabel etiquetaExp;
    public javax.swing.JButton goBack1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelIcon4;
    public javax.swing.JRadioButton rb1AbandonodelTexConMejoria;
    public javax.swing.JRadioButton rb1AbandonodelTxSinMejoria;
    public javax.swing.JRadioButton rb1AltaPorMejoria;
    public javax.swing.JRadioButton rb1Baja;
    public javax.swing.JRadioButton rb1CumplioObjetivosdelTx;
    public javax.swing.JRadioButton rb1VoluntarioConMejoria;
    public javax.swing.JRadioButton rb1VoluntarioSinMejoria;
    public javax.swing.JRadioButton rb2FaseDiagnostica;
    public javax.swing.JRadioButton rb2TratamientoReinsercionSocial;
    public javax.swing.JTextArea txt3_MotivoEgreso;
    public javax.swing.JTextArea txt4_areamedica;
    public javax.swing.JTextArea txt4_areapsicologia;
    public javax.swing.JTextArea txt4_areasocial;
    public javax.swing.JTextArea txt5_Dareamedica;
    public javax.swing.JTextArea txt5_Dareapsicologia;
    public javax.swing.JTextArea txt5_Dareasocial;
    public javax.swing.JTextArea txt5_areamedica;
    public javax.swing.JTextArea txt5_areapsicologia;
    public javax.swing.JTextArea txt5_areasocial;
    public javax.swing.JTextArea txt6_PronosticoEgreso;
    public javax.swing.JTextArea txt7_Sugerencias;
    public javax.swing.JTextArea txt8_Observaciones;
    // End of variables declaration//GEN-END:variables
}
