/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Psicologo;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author YareMtz
 */
public class JFPrueba extends javax.swing.JFrame {

    /**
     * Creates new form JFPrueba
     */
    public JFPrueba() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Image icon = new ImageIcon(getClass().getResource("/imagenes/solo-unemecapa.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelIcon2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        labeNumExp = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtPAciente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rbAssit = new javax.swing.JRadioButton();
        rbPosit = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        rbpiba = new javax.swing.JRadioButton();
        rbibbp = new javax.swing.JRadioButton();
        rbibum = new javax.swing.JRadioButton();
        rbtbuc = new javax.swing.JRadioButton();
        rbibmf = new javax.swing.JRadioButton();
        rbpsc = new javax.swing.JRadioButton();
        rbppr = new javax.swing.JRadioButton();
        rbpibfamiliaresusuarios = new javax.swing.JRadioButton();
        rbpibadolescentesnoconsu = new javax.swing.JRadioButton();
        rbconsejobreve = new javax.swing.JRadioButton();
        rbintervencionbreve = new javax.swing.JRadioButton();
        rbPropar = new javax.swing.JRadioButton();
        jSeparator8 = new javax.swing.JSeparator();
        txtnumsesiones = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtResponsable = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Unidad de Especialidad Médica - Centro de Atención Primaria en Adicciones");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel7FocusLost(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(139, 165, 155));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chilpancingo, Guerrero, México.");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Calle Venustiano Carranza No. 18, Col. 20 de noviembre, C.P. 39096");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 20));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 730, 30));

        labelIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGO.png"))); // NOI18N
        jPanel7.add(labelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 60));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        jPanel7.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 140, 40));

        labeNumExp.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        labeNumExp.setText("Núm. Expediente: ####-####");
        jPanel7.add(labeNumExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, 20));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel7.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 140, 40));

        jLabel21.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel21.setText("Nombre:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, 30));
        jPanel7.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 460, 10));

        txtPAciente.setEditable(false);
        txtPAciente.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        txtPAciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPAciente.setToolTipText("");
        txtPAciente.setBorder(null);
        jPanel7.add(txtPAciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 460, 30));

        jLabel22.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel22.setText("Prueba realizada:");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        buttonGroup1.add(rbAssit);
        rbAssit.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbAssit.setText("ASSIT");
        rbAssit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAssitActionPerformed(evt);
            }
        });
        jPanel7.add(rbAssit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        buttonGroup1.add(rbPosit);
        rbPosit.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbPosit.setText("POSIT");
        jPanel7.add(rbPosit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Intervención", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Heiti TC", 0, 13))); // NOI18N

        buttonGroup2.add(rbpiba);
        rbpiba.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbpiba.setText("PIBA");
        rbpiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpibaActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbibbp);
        rbibbp.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbibbp.setText("IBBP");

        buttonGroup2.add(rbibum);
        rbibum.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbibum.setText("IBUM");
        rbibum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbibumActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtbuc);
        rbtbuc.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbtbuc.setText("TBUC");

        buttonGroup2.add(rbibmf);
        rbibmf.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbibmf.setText("IBMF");
        rbibmf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbibmfActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbpsc);
        rbpsc.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbpsc.setText("PSC");

        buttonGroup2.add(rbppr);
        rbppr.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbppr.setText("PPR");
        rbppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpprActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbpibfamiliaresusuarios);
        rbpibfamiliaresusuarios.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbpibfamiliaresusuarios.setText("Programa de intervención breve para familiares de usuarios (urbano/rural)");

        buttonGroup2.add(rbpibadolescentesnoconsu);
        rbpibadolescentesnoconsu.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbpibadolescentesnoconsu.setText("Programa de intervención breve para adolescentes no consumidores");
        rbpibadolescentesnoconsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpibadolescentesnoconsuActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbconsejobreve);
        rbconsejobreve.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbconsejobreve.setText("Consejo breve");
        rbconsejobreve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbconsejobreveActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbintervencionbreve);
        rbintervencionbreve.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbintervencionbreve.setText("Intervención breve");
        rbintervencionbreve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbintervencionbreveActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbPropar);
        rbPropar.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        rbPropar.setText("PROPAR");
        rbPropar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbpsc)
                    .addComponent(rbibmf)
                    .addComponent(rbtbuc)
                    .addComponent(rbibum)
                    .addComponent(rbibbp)
                    .addComponent(rbpiba))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbintervencionbreve)
                    .addComponent(rbconsejobreve)
                    .addComponent(rbpibadolescentesnoconsu)
                    .addComponent(rbpibfamiliaresusuarios)
                    .addComponent(rbppr)
                    .addComponent(rbPropar))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbppr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbpibfamiliaresusuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbpibadolescentesnoconsu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPropar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbpiba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbibbp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbibum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtbuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbibmf)
                            .addComponent(rbconsejobreve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbpsc)
                            .addComponent(rbintervencionbreve))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 670, 230));
        jPanel7.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 280, 10));

        txtnumsesiones.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        txtnumsesiones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnumsesiones.setToolTipText("");
        txtnumsesiones.setBorder(null);
        jPanel7.add(txtnumsesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 280, 30));

        jLabel23.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel23.setText("Número de sesiones programadas:");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 30));

        jPanel9.setBackground(new java.awt.Color(0, 138, 58));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prueba ASSIT/POSIT");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, 30));

        jLabel24.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel24.setText("Nombre del responsable:");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 30));
        jPanel7.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 460, 10));

        txtResponsable.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        txtResponsable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResponsable.setToolTipText("");
        txtResponsable.setBorder(null);
        jPanel7.add(txtResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 460, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel7FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7FocusLost

    private void rbAssitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAssitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAssitActionPerformed

    private void rbpibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbpibaActionPerformed

    private void rbibumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbibumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbibumActionPerformed

    private void rbibmfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbibmfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbibmfActionPerformed

    private void rbpprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbpprActionPerformed

    private void rbpibadolescentesnoconsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpibadolescentesnoconsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbpibadolescentesnoconsuActionPerformed

    private void rbintervencionbreveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbintervencionbreveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbintervencionbreveActionPerformed

    private void rbconsejobreveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbconsejobreveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbconsejobreveActionPerformed

    private void rbProparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbProparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel labeNumExp;
    private javax.swing.JLabel labelIcon2;
    public javax.swing.JRadioButton rbAssit;
    public javax.swing.JRadioButton rbPosit;
    public javax.swing.JRadioButton rbPropar;
    public javax.swing.JRadioButton rbconsejobreve;
    public javax.swing.JRadioButton rbibbp;
    public javax.swing.JRadioButton rbibmf;
    public javax.swing.JRadioButton rbibum;
    public javax.swing.JRadioButton rbintervencionbreve;
    public javax.swing.JRadioButton rbpiba;
    public javax.swing.JRadioButton rbpibadolescentesnoconsu;
    public javax.swing.JRadioButton rbpibfamiliaresusuarios;
    public javax.swing.JRadioButton rbppr;
    public javax.swing.JRadioButton rbpsc;
    public javax.swing.JRadioButton rbtbuc;
    public javax.swing.JTextField txtPAciente;
    public javax.swing.JTextField txtResponsable;
    public javax.swing.JTextField txtnumsesiones;
    // End of variables declaration//GEN-END:variables
}
