/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.TrabajadorSocial;

import Modelo.Boton;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author YareMtz
 */
public class JFPacientesTrabajadorSocial extends javax.swing.JFrame {
    Boton btn = new Boton();
    /**
     * Creates new form JFFichasIdentificacion
     */
    public JFPacientesTrabajadorSocial() {
        initComponents();
        btnNotasPDF.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
        Image icon = new ImageIcon(getClass().getResource("/imagenes/solo-unemecapa.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Empleados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_Referencias = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        btnFichaIdentificacion = new javax.swing.JButton();
        btnEstudioSocialSocioeconomico = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NumEmpleado = new javax.swing.JLabel();
        btnNuevoPaciente = new javax.swing.JButton();
        btnNotasRescate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnPdfEstSocSoc = new javax.swing.JButton();
        btnPdfFicha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbPaciente = new javax.swing.JComboBox<>();
        btnNotasPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Unidad de Especialidad Médica - Centro de Atención Primaria en Adicciones");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 138, 58));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pacientes - Fichas de identificación");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 950, 30));

        jPanel3.setBackground(new java.awt.Color(0, 98, 39));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Empleados.setBackground(new java.awt.Color(58, 156, 112));
        btn_Empleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-conference_background_selected.png"))); // NOI18N
        btn_Empleados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        jLabel5.setBackground(new java.awt.Color(58, 156, 112));
        jLabel5.setFont(new java.awt.Font("Champagne & Limousines", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pacientes");
        btn_Empleados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        jPanel3.add(btn_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 230, 49));

        btn_Logout.setBackground(new java.awt.Color(0, 109, 75));
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_LogoutMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
        });
        btn_Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-exit.png"))); // NOI18N
        btn_Logout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        jLabel7.setText("Cerrar sesión");
        jLabel7.setFont(new java.awt.Font("Champagne & Limousines", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        jPanel3.add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, -1));

        btn_Referencias.setBackground(new java.awt.Color(0, 109, 75));
        btn_Referencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ReferenciasMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ReferenciasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ReferenciasMouseEntered(evt);
            }
        });
        btn_Referencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-sorting_arrows_horizontal.png"))); // NOI18N
        btn_Referencias.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        jLabel9.setFont(new java.awt.Font("Champagne & Limousines", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Referencias");
        btn_Referencias.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        jPanel3.add(btn_Referencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 660));

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGO.png"))); // NOI18N
        jPanel1.add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, 60));

        jScrollPane1.setRowHeaderView(null);

        tablaPacientes.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Exp.", "Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPacientes.setSelectionBackground(new java.awt.Color(0, 102, 0));
        jScrollPane1.setViewportView(tablaPacientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 590, 270));

        btnFichaIdentificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-identity_theft_1.png"))); // NOI18N
        btnFichaIdentificacion.setText("Ficha de identificación");
        btnFichaIdentificacion.setBackground(new java.awt.Color(255, 255, 255));
        btnFichaIdentificacion.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnFichaIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaIdentificacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnFichaIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 250, 40));

        btnEstudioSocialSocioeconomico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-view_file.png"))); // NOI18N
        btnEstudioSocialSocioeconomico.setText("Estudio Social/Socieconomico");
        btnEstudioSocialSocioeconomico.setBackground(new java.awt.Color(255, 255, 255));
        btnEstudioSocialSocioeconomico.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnEstudioSocialSocioeconomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudioSocialSocioeconomicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstudioSocialSocioeconomico, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, -1, 40));

        jPanel8.setBackground(new java.awt.Color(139, 165, 155));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chilpancingo, Guerrero, México.");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 20));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Calle Venustiano Carranza No. 18, Col. 20 de noviembre, C.P. 39096");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 20));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 950, 30));
        jPanel1.add(NumEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 240, 40));

        btnNuevoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoPaciente.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnNuevoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-plus.png"))); // NOI18N
        btnNuevoPaciente.setText("Nuevo");
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 120, 40));

        btnNotasRescate.setBackground(new java.awt.Color(255, 255, 255));
        btnNotasRescate.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnNotasRescate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-end_call.png"))); // NOI18N
        btnNotasRescate.setText("Notas de rescate");
        btnNotasRescate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasRescateActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotasRescate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 250, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 300, -1));

        btnPdfEstSocSoc.setBackground(new java.awt.Color(255, 255, 255));
        btnPdfEstSocSoc.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnPdfEstSocSoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-pdf_2.png"))); // NOI18N
        btnPdfEstSocSoc.setToolTipText("Siguiente parte del formato de egreso");
        jPanel1.add(btnPdfEstSocSoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, -1, -1));

        btnPdfFicha.setBackground(new java.awt.Color(255, 255, 255));
        btnPdfFicha.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnPdfFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-pdf_2.png"))); // NOI18N
        btnPdfFicha.setToolTipText("Siguiente parte del formato de egreso");
        jPanel1.add(btnPdfFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, -1, -1));

        jLabel2.setText("Paciente");
        jLabel2.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        cbPaciente.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel1.add(cbPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 440, 40));

        btnNotasPDF.setBackground(new java.awt.Color(255, 255, 255));
        btnNotasPDF.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btnNotasPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-pdf_2.png"))); // NOI18N
        btnNotasPDF.setToolTipText("Siguiente parte del formato de egreso");
        jPanel1.add(btnNotasPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMousePressed

    }//GEN-LAST:event_btn_LogoutMousePressed

    private void btn_ReferenciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReferenciasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ReferenciasMousePressed

    private void btnFichaIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFichaIdentificacionActionPerformed

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusLost

    private void btnEstudioSocialSocioeconomicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudioSocialSocioeconomicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudioSocialSocioeconomicoActionPerformed

    private void btn_ReferenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReferenciasMouseExited
        btn.resetColorMenu(btn_Referencias);
    }//GEN-LAST:event_btn_ReferenciasMouseExited

    private void btn_ReferenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReferenciasMouseEntered
        btn.setColorSelectedMenu(btn_Referencias);
    }//GEN-LAST:event_btn_ReferenciasMouseEntered

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        btn.setColorSelectedMenu(btn_Logout);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
        btn.resetColorMenu(btn_Logout);
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoPacienteActionPerformed

    private void btnNotasRescateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasRescateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotasRescateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPacientesTrabajadorSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPacientesTrabajadorSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPacientesTrabajadorSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPacientesTrabajadorSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPacientesTrabajadorSocial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel NumEmpleado;
    public javax.swing.JButton btnEstudioSocialSocioeconomico;
    public javax.swing.JButton btnFichaIdentificacion;
    public javax.swing.JButton btnNotasPDF;
    public javax.swing.JButton btnNotasRescate;
    public javax.swing.JButton btnNuevoPaciente;
    public javax.swing.JButton btnPdfEstSocSoc;
    public javax.swing.JButton btnPdfFicha;
    public javax.swing.JPanel btn_Empleados;
    public javax.swing.JPanel btn_Logout;
    public javax.swing.JPanel btn_Referencias;
    public javax.swing.JComboBox<String> cbPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelIcon;
    public javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
