/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Recepcionista;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author YareMtz
 */
public class JFRegistrarCita extends javax.swing.JFrame {

    /**
     * Creates new form JFRegistrarCita
     */
    public JFRegistrarCita() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        txtObservaciones.setOpaque(false);
        Image icon = new ImageIcon(getClass().getResource("/imagenes/solo-unemecapa.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        etiquetaAccion = new javax.swing.JLabel();
        labelIcon2 = new javax.swing.JLabel();
        btnCancelarCita = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        txtNombrePAciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbTipoCita = new javax.swing.JComboBox<>();
        separador = new javax.swing.JSeparator();
        txtIntervencion = new javax.swing.JTextField();
        labelinter = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        dpFechaCita = new com.github.lgooddatepicker.components.DatePicker();
        tcHora = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_GuardarCita = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Unidad de Especialidad Médica - Centro de Atención Primaria en Adicciones");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel7FocusLost(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 138, 58));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaAccion.setText("Registrar cita");
        etiquetaAccion.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        etiquetaAccion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(etiquetaAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, 30));

        labelIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGO.png"))); // NOI18N
        jPanel7.add(labelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, 60));

        btnCancelarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-cancel.png"))); // NOI18N
        btnCancelarCita.setText("Cancelar");
        btnCancelarCita.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarCita.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel7.add(btnCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 140, 40));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Heiti TC", 0, 13))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 330, -1));

        txtNombrePAciente.setEditable(false);
        txtNombrePAciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombrePAciente.setBorder(null);
        txtNombrePAciente.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        txtNombrePAciente.setToolTipText("");
        jPanel10.add(txtNombrePAciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 330, 30));

        jLabel11.setText("Observaciones");
        jLabel11.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setText("Paciente:");
        jLabel6.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel7.setText("Fecha:");
        jLabel7.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 30));

        cbTipoCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Psicologica", "Medica" }));
        cbTipoCita.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel10.add(cbTipoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));
        jPanel10.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 680, -1));

        txtIntervencion.setEditable(false);
        txtIntervencion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIntervencion.setBorder(null);
        txtIntervencion.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        txtIntervencion.setToolTipText("");
        jPanel10.add(txtIntervencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 680, 30));

        labelinter.setText("Intervención");
        labelinter.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel10.add(labelinter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        txtObservaciones.setBorder(null);
        txtObservaciones.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        txtObservaciones.setOpaque(false);
        txtObservaciones.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtObservaciones.setSelectionColor(new java.awt.Color(0, 98, 39));
        jScrollPane3.setViewportView(txtObservaciones);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 660, 90));
        jPanel10.add(dpFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        tcHora.setOpaque(true);
        jPanel10.add(tcHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 30));

        jLabel9.setText("Cita:");
        jLabel9.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, 20));

        jLabel10.setText("Hora:");
        jLabel10.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, 30));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 750, 400));

        btn_GuardarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-save.png"))); // NOI18N
        btn_GuardarCita.setText("Guardar");
        btn_GuardarCita.setBackground(new java.awt.Color(255, 255, 255));
        btn_GuardarCita.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel7.add(btn_GuardarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 140, 40));

        jPanel9.setBackground(new java.awt.Color(139, 165, 155));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Chilpancingo, Guerrero, México.");
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 20));

        jLabel5.setText("Calle Venustiano Carranza No. 18, Col. 20 de noviembre, C.P. 39096");
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 20));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 750, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel7FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegistrarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegistrarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarCita;
    public javax.swing.JButton btn_GuardarCita;
    public javax.swing.JComboBox<String> cbTipoCita;
    public com.github.lgooddatepicker.components.DatePicker dpFechaCita;
    public javax.swing.JLabel etiquetaAccion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelIcon2;
    public javax.swing.JLabel labelinter;
    public javax.swing.JSeparator separador;
    public lu.tudor.santec.jtimechooser.JTimeChooser tcHora;
    public javax.swing.JTextField txtIntervencion;
    public javax.swing.JTextField txtNombrePAciente;
    public javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
