/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Administrador;

import Modelo.Boton;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author YareMtz
 */
public class JFEmpleados extends javax.swing.JFrame {
    Boton btn = new Boton();
    /**
     * Creates new form JFEmpleados
     */
    public JFEmpleados() {
        initComponents();
        
        Image icon = new ImageIcon(getClass().getResource("/imagenes/solo-unemecapa.png")).getImage();
        setIconImage(icon);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogSuccess = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        labelAccion5 = new javax.swing.JLabel();
        TituloMsg2 = new javax.swing.JLabel();
        btnAceptar2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        labelAccion6 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Establecimientos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Empleados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        btn_Actualizar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_AgregarEmpleado = new javax.swing.JButton();
        btn_Responsable = new javax.swing.JButton();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel8FocusLost(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAccion5.setFont(new java.awt.Font("Heiti TC", 0, 16)); // NOI18N
        labelAccion5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-ok.png"))); // NOI18N
        jPanel8.add(labelAccion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, 80));

        TituloMsg2.setFont(new java.awt.Font("Heiti TC", 0, 16)); // NOI18N
        TituloMsg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloMsg2.setText("Operación exitosa");
        jPanel8.add(TituloMsg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 310, 30));

        btnAceptar2.setBackground(new java.awt.Color(69, 167, 94));
        btnAceptar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAceptar2MousePressed(evt);
            }
        });
        btnAceptar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAceptar2KeyPressed(evt);
            }
        });
        btnAceptar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 138, 58));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnAceptar2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 310, 10));

        labelAccion6.setFont(new java.awt.Font("Heiti TC", 0, 16)); // NOI18N
        labelAccion6.setForeground(new java.awt.Color(255, 255, 255));
        labelAccion6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAccion6.setText("Aceptar");
        btnAceptar2.add(labelAccion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));

        jPanel8.add(btnAceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 210, 40));

        msg.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setText("El registro se ha realizado correctamente");
        msg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msgKeyPressed(evt);
            }
        });
        jPanel8.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, 140));

        javax.swing.GroupLayout jDialogSuccessLayout = new javax.swing.GroupLayout(jDialogSuccess.getContentPane());
        jDialogSuccess.getContentPane().setLayout(jDialogSuccessLayout);
        jDialogSuccessLayout.setHorizontalGroup(
            jDialogSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogSuccessLayout.setVerticalGroup(
            jDialogSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSuccessLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Unidad de Especialidad Médica - Centro de Atención Primaria en Adicciones");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 138, 58));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de empleados");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 950, 30));

        jPanel3.setBackground(new java.awt.Color(0, 98, 39));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Establecimientos.setBackground(new java.awt.Color(0, 109, 75));
        btn_Establecimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_EstablecimientosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EstablecimientosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EstablecimientosMouseEntered(evt);
            }
        });
        btn_Establecimientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-barn.png"))); // NOI18N
        btn_Establecimientos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        jLabel3.setFont(new java.awt.Font("Champagne & Limousines", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Establecimientos");
        btn_Establecimientos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 50));

        jPanel3.add(btn_Establecimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 50));

        btn_Empleados.setBackground(new java.awt.Color(58, 156, 112));
        btn_Empleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-commercial_development_management.png"))); // NOI18N
        btn_Empleados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        jLabel5.setFont(new java.awt.Font("Champagne & Limousines", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Empleados");
        btn_Empleados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 50));

        jPanel3.add(btn_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 230, 49));

        btn_Logout.setBackground(new java.awt.Color(0, 109, 75));
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
        });
        btn_Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-exit.png"))); // NOI18N
        btn_Logout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        jLabel7.setFont(new java.awt.Font("Champagne & Limousines", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cerrar sesión");
        btn_Logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 50));

        jPanel3.add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 660));

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGO.png"))); // NOI18N
        jPanel1.add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, 60));

        jScrollPane1.setRowHeaderView(null);

        tablaEmpleados.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Francisco Blanco", "17282828", "Coordinador", "Matutino", "Activo"},
                {"2", "Yaretzin Mtz", "98198298289", "Medico", "Vespertino", "Activo"}
            },
            new String [] {
                "ID", "Nombre", "Cédula", "Puesto", "Turno", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleados.setSelectionBackground(new java.awt.Color(0, 102, 0));
        jScrollPane1.setViewportView(tablaEmpleados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 820, 360));

        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-edit_file.png"))); // NOI18N
        btn_Actualizar.setText("Editar");
        btn_Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Actualizar.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jPanel1.add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 140, 40));

        jPanel9.setBackground(new java.awt.Color(139, 165, 155));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Chilpancingo, Guerrero, México.");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 20));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Calle Venustiano Carranza No. 18, Col. 20 de noviembre, C.P. 39096");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 20));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 950, 30));

        btn_AgregarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btn_AgregarEmpleado.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btn_AgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-add_user.png"))); // NOI18N
        btn_AgregarEmpleado.setText("Agregar");
        jPanel1.add(btn_AgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 140, 40));

        btn_Responsable.setBackground(new java.awt.Color(255, 255, 255));
        btn_Responsable.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        btn_Responsable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/icons8-manager.png"))); // NOI18N
        btn_Responsable.setText("Responsable UNEME-CAPA");
        jPanel1.add(btn_Responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusLost

    private void btn_EstablecimientosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EstablecimientosMousePressed
        
    }//GEN-LAST:event_btn_EstablecimientosMousePressed

    private void btn_EstablecimientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EstablecimientosMouseEntered
        btn.setColorSelectedMenu(btn_Establecimientos);
    }//GEN-LAST:event_btn_EstablecimientosMouseEntered

    private void btn_EstablecimientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EstablecimientosMouseExited
        btn.resetColorMenu(btn_Establecimientos);
    }//GEN-LAST:event_btn_EstablecimientosMouseExited

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        btn.setColorSelectedMenu(btn_Logout);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
        btn.resetColorMenu(btn_Logout);
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btnAceptar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptar2MousePressed
        this.dispose();
    }//GEN-LAST:event_btnAceptar2MousePressed

    private void btnAceptar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAceptar2KeyPressed

    }//GEN-LAST:event_btnAceptar2KeyPressed

    private void msgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msgKeyPressed

    }//GEN-LAST:event_msgKeyPressed

    private void jPanel8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel8FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8FocusLost

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel TituloMsg2;
    public javax.swing.JPanel btnAceptar2;
    public javax.swing.JButton btn_Actualizar;
    public javax.swing.JButton btn_AgregarEmpleado;
    public javax.swing.JPanel btn_Empleados;
    public javax.swing.JPanel btn_Establecimientos;
    public javax.swing.JPanel btn_Logout;
    public javax.swing.JButton btn_Responsable;
    public javax.swing.JDialog jDialogSuccess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelAccion5;
    public javax.swing.JLabel labelAccion6;
    private javax.swing.JLabel labelIcon;
    public javax.swing.JLabel msg;
    public javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
