package Modelo;
// Generated 29-nov-2017 14:40:39 by Hibernate Tools 4.3.1



/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private Integer idDomicilio;
     private String calle;
     private String numero;
     private String colonia;
     private String codigoPostal;
     private String delegacionMunicipio;
     private String entidadLocalidad;
     private String estado;

    public Domicilio() {
    }

	
    public Domicilio(String calle, String numero, String delegacionMunicipio, String entidadLocalidad, String estado) {
        this.calle = calle;
        this.numero = numero;
        this.delegacionMunicipio = delegacionMunicipio;
        this.entidadLocalidad = entidadLocalidad;
        this.estado = estado;
    }
    public Domicilio(String calle, String numero, String colonia, String codigoPostal, String delegacionMunicipio, String entidadLocalidad, String estado) {
       this.calle = calle;
       this.numero = numero;
       this.colonia = colonia;
       this.codigoPostal = codigoPostal;
       this.delegacionMunicipio = delegacionMunicipio;
       this.entidadLocalidad = entidadLocalidad;
       this.estado = estado;
    }
   
    public Integer getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(Integer idDomicilio) {
        this.idDomicilio = idDomicilio;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getDelegacionMunicipio() {
        return this.delegacionMunicipio;
    }
    
    public void setDelegacionMunicipio(String delegacionMunicipio) {
        this.delegacionMunicipio = delegacionMunicipio;
    }
    public String getEntidadLocalidad() {
        return this.entidadLocalidad;
    }
    
    public void setEntidadLocalidad(String entidadLocalidad) {
        this.entidadLocalidad = entidadLocalidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


