package Modelo;
// Generated 29-nov-2017 14:40:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Extramuro generated by hbm2java
 */
public class Extramuro  implements java.io.Serializable {


     private Integer idExtramuro;
     private String actividad;
     private String lugar;
     private Date fecha;
     private Date hora;

    public Extramuro() {
    }

    public Extramuro(String actividad, String lugar, Date fecha, Date hora) {
       this.actividad = actividad;
       this.lugar = lugar;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdExtramuro() {
        return this.idExtramuro;
    }
    
    public void setIdExtramuro(Integer idExtramuro) {
        this.idExtramuro = idExtramuro;
    }
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


