package Modelo;
// Generated 29-nov-2017 14:40:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NotaMedica generated by hbm2java
 */
public class NotaMedica  implements java.io.Serializable {


     private Integer idNotaMedica;
     private Date fechaNotaMedica;
     private String resumen;
     private Integer idEmpleado;
     private Integer idExpediente;

    public NotaMedica() {
    }

    public NotaMedica(Date fechaNotaMedica, String resumen, Integer idEmpleado, Integer idExpediente) {
       this.fechaNotaMedica = fechaNotaMedica;
       this.resumen = resumen;
       this.idEmpleado = idEmpleado;
       this.idExpediente = idExpediente;
    }
   
    public Integer getIdNotaMedica() {
        return this.idNotaMedica;
    }
    
    public void setIdNotaMedica(Integer idNotaMedica) {
        this.idNotaMedica = idNotaMedica;
    }
    public Date getFechaNotaMedica() {
        return this.fechaNotaMedica;
    }
    
    public void setFechaNotaMedica(Date fechaNotaMedica) {
        this.fechaNotaMedica = fechaNotaMedica;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }




}


