package Modelo;
// Generated 29-nov-2017 14:40:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NotaRescate generated by hbm2java
 */
public class NotaRescate  implements java.io.Serializable {


     private Integer idNotaRescate;
     private Date fechaLlamada;
     private Date horaLlamada;
     private Integer idUltimaCita;
     private Integer idProximaCita;
     private String observaciones;
     private Integer idEmpleado;
     private Integer idExpediente;

    public NotaRescate() {
    }

	
    public NotaRescate(Date fechaLlamada, Date horaLlamada) {
        this.fechaLlamada = fechaLlamada;
        this.horaLlamada = horaLlamada;
    }
    public NotaRescate(Date fechaLlamada, Date horaLlamada, Integer idUltimaCita, Integer idProximaCita, String observaciones, Integer idEmpleado, Integer idExpediente) {
       this.fechaLlamada = fechaLlamada;
       this.horaLlamada = horaLlamada;
       this.idUltimaCita = idUltimaCita;
       this.idProximaCita = idProximaCita;
       this.observaciones = observaciones;
       this.idEmpleado = idEmpleado;
       this.idExpediente = idExpediente;
    }
   
    public Integer getIdNotaRescate() {
        return this.idNotaRescate;
    }
    
    public void setIdNotaRescate(Integer idNotaRescate) {
        this.idNotaRescate = idNotaRescate;
    }
    public Date getFechaLlamada() {
        return this.fechaLlamada;
    }
    
    public void setFechaLlamada(Date fechaLlamada) {
        this.fechaLlamada = fechaLlamada;
    }
    public Date getHoraLlamada() {
        return this.horaLlamada;
    }
    
    public void setHoraLlamada(Date horaLlamada) {
        this.horaLlamada = horaLlamada;
    }
    public Integer getIdUltimaCita() {
        return this.idUltimaCita;
    }
    
    public void setIdUltimaCita(Integer idUltimaCita) {
        this.idUltimaCita = idUltimaCita;
    }
    public Integer getIdProximaCita() {
        return this.idProximaCita;
    }
    
    public void setIdProximaCita(Integer idProximaCita) {
        this.idProximaCita = idProximaCita;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }




}


