package Modelo;
// Generated 29-nov-2017 14:40:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NotaTratamiento generated by hbm2java
 */
public class NotaTratamiento  implements java.io.Serializable {


     private Integer idNotaTratamiento;
     private Date fechaNotaTratamiento;
     private Date horaInicioNotaTratamiento;
     private String servicioOtorgado;
     private String resumenSesion;
     private String pronosticoTratamiento;
     private Integer idEmpleado;
     private Date horaFinNotaTratamiento;
     private Integer idExpediente;
     private String diagnostico;

    public NotaTratamiento() {
    }

    public NotaTratamiento(Date fechaNotaTratamiento, Date horaInicioNotaTratamiento, String servicioOtorgado, String resumenSesion, String pronosticoTratamiento, Integer idEmpleado, Date horaFinNotaTratamiento, Integer idExpediente, String diagnostico) {
       this.fechaNotaTratamiento = fechaNotaTratamiento;
       this.horaInicioNotaTratamiento = horaInicioNotaTratamiento;
       this.servicioOtorgado = servicioOtorgado;
       this.resumenSesion = resumenSesion;
       this.pronosticoTratamiento = pronosticoTratamiento;
       this.idEmpleado = idEmpleado;
       this.horaFinNotaTratamiento = horaFinNotaTratamiento;
       this.idExpediente = idExpediente;
       this.diagnostico = diagnostico;
    }
   
    public Integer getIdNotaTratamiento() {
        return this.idNotaTratamiento;
    }
    
    public void setIdNotaTratamiento(Integer idNotaTratamiento) {
        this.idNotaTratamiento = idNotaTratamiento;
    }
    public Date getFechaNotaTratamiento() {
        return this.fechaNotaTratamiento;
    }
    
    public void setFechaNotaTratamiento(Date fechaNotaTratamiento) {
        this.fechaNotaTratamiento = fechaNotaTratamiento;
    }
    public Date getHoraInicioNotaTratamiento() {
        return this.horaInicioNotaTratamiento;
    }
    
    public void setHoraInicioNotaTratamiento(Date horaInicioNotaTratamiento) {
        this.horaInicioNotaTratamiento = horaInicioNotaTratamiento;
    }
    public String getServicioOtorgado() {
        return this.servicioOtorgado;
    }
    
    public void setServicioOtorgado(String servicioOtorgado) {
        this.servicioOtorgado = servicioOtorgado;
    }
    public String getResumenSesion() {
        return this.resumenSesion;
    }
    
    public void setResumenSesion(String resumenSesion) {
        this.resumenSesion = resumenSesion;
    }
    public String getPronosticoTratamiento() {
        return this.pronosticoTratamiento;
    }
    
    public void setPronosticoTratamiento(String pronosticoTratamiento) {
        this.pronosticoTratamiento = pronosticoTratamiento;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Date getHoraFinNotaTratamiento() {
        return this.horaFinNotaTratamiento;
    }
    
    public void setHoraFinNotaTratamiento(Date horaFinNotaTratamiento) {
        this.horaFinNotaTratamiento = horaFinNotaTratamiento;
    }
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }

    public String getDiagnostico() {
        return diagnostico;
    }

    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }

    


}


