package Modelo;
// Generated 29-nov-2017 14:40:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer idPaciente;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String sexo;
     private Date fechaNac;
     private String estadoCivil;
     private String municipioNacimiento;
     private String estadoNacimiento;
     private String ocupacion;
     private String rfc;
     private String curp;
     private String telefono;
     private String celular;
     private Integer idDomicilio;

    public Paciente() {
    }

	
    public Paciente(String nombre, String apellidoPaterno, String apellidoMaterno, String sexo, Date fechaNac) {
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.sexo = sexo;
        this.fechaNac = fechaNac;
    }
    public Paciente(String nombre, String apellidoPaterno, String apellidoMaterno, String sexo, Date fechaNac, String estadoCivil, String municipioNacimiento, String estadoNacimiento, String ocupacion, String rfc, String curp, String telefono, String celular, Integer idDomicilio) {
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.sexo = sexo;
       this.fechaNac = fechaNac;
       this.estadoCivil = estadoCivil;
       this.municipioNacimiento = municipioNacimiento;
       this.estadoNacimiento = estadoNacimiento;
       this.ocupacion = ocupacion;
       this.rfc = rfc;
       this.curp = curp;
       this.telefono = telefono;
       this.celular = celular;
       this.idDomicilio = idDomicilio;
    }
   
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getMunicipioNacimiento() {
        return this.municipioNacimiento;
    }
    
    public void setMunicipioNacimiento(String municipioNacimiento) {
        this.municipioNacimiento = municipioNacimiento;
    }
    public String getEstadoNacimiento() {
        return this.estadoNacimiento;
    }
    
    public void setEstadoNacimiento(String estadoNacimiento) {
        this.estadoNacimiento = estadoNacimiento;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Integer getIdDomicilio() {
        return this.idDomicilio;
    }
    
    public void setIdDomicilio(Integer idDomicilio) {
        this.idDomicilio = idDomicilio;
    }




}


