package Modelo;
// Generated 29-nov-2017 14:40:39 by Hibernate Tools 4.3.1



/**
 * RespuestasEncuesta generated by hbm2java
 */
public class RespuestasEncuesta  implements java.io.Serializable {


     private Long idRespuesta;
     private String valorRespuesta;
     private int idPregunta;
     private int idEmpleado;
     private int idExpediente;

    public RespuestasEncuesta() {
    }

    public RespuestasEncuesta(String valorRespuesta, int idPregunta) {
        this.valorRespuesta = valorRespuesta;
        this.idPregunta = idPregunta;
    }
    
    

	
    public RespuestasEncuesta(int idPregunta, int idEmpleado, int idExpediente) {
        this.idPregunta = idPregunta;
        this.idEmpleado = idEmpleado;
        this.idExpediente = idExpediente;
    }
    public RespuestasEncuesta(String valorRespuesta, int idPregunta, int idEmpleado, int idExpediente) {
       this.valorRespuesta = valorRespuesta;
       this.idPregunta = idPregunta;
       this.idEmpleado = idEmpleado;
       this.idExpediente = idExpediente;
    }
   
    public Long getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Long idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public String getValorRespuesta() {
        return this.valorRespuesta;
    }
    
    public void setValorRespuesta(String valorRespuesta) {
        this.valorRespuesta = valorRespuesta;
    }
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(int idExpediente) {
        this.idExpediente = idExpediente;
    }




}


